title: Cuihua (Cindy) Shen, Ph.D.
logo: /assets/cuihua-shen.jpg
description: Professor of Communication at the University of California, Davis.
theme: jekyll-theme-minimal
show_downloads: false
google_analytics:
